### ISSUE TITLE
versatiles serve "data.versatiles#osm" feels wrong. Any other character than "#"?

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles#5]
maybe use brackets like "../file/data.versatiles[osm]"

**Comment by yetzt** [comment]
use colon `:` .

**Comment by MichaelKreil** [comment]
But versatiles also accepts urls like "https://..." so colons are already in use :/

**Comment by yetzt** [comment]
ah, i see. then `#` fragments make sense in the url context, if you don't want to do some querytring shenanigans like `?[...]dataset=osm`. there is not really a good way to have the same "refer to something within a file" functionality in file paths. 

when in doubt, use a parameter for the executable `--dataset=osm` instead of trying to shoehorn it into the url/filepath. then there is no conflict.
